batch_size: 24
epochs: 5
expert_dim: 1024
lr: 0.001
model_names:
- openai/whisper-large-v3
n_mels: 80
num_workers: 4
output_dir: /home/an.dangthithuy/khanhtl/TeaMoE/checkpoints/pretrained
train_manifest: datasets/processed_data_librispeech/manifests/train.jsonl
valid_manifest: datasets/processed_data_librispeech/manifests/validation.jsonl
